### ISSUE TITLE
same code as a plugin

### ISSUE THREAD

**Issue by MCPEPIG** [matcracker/StafferList#3]
This plugin has the same code as a plugin made by xFlare

**Comment by matcracker** [comment]
What? It is simplex plugin... I watch API Documentation and it is very simplex code...

**Comment by matcracker** [comment]
And what plugin?

**Comment by MCPEPIG** [comment]
-.-

**Comment by Gamecrafter** [comment]
I think he's talking about xFlare's xRulesx...

**Comment by MCPEPIG** [comment]
Yeah

**Comment by Gamecrafter** [comment]
It looks alike, but I doubt he was copying. That's the basic way to call a string from a config file.

**Comment by matcracker** [comment]
I watch the code of plugin xRulesx... Yes, it very similar to my plugin but how said GameCrafter that the BASIC way to call a stringe from config file.

**Comment by Gamecrafter** [comment]
You can find that in my plugins too. Basic way, no copying involved. :+1:

**Comment by Gamecrafter** [comment]
Compare at www.github.com/gamecrafter/small-plugins/tree/master/serverlaw
